### ISSUE TITLE
Translation editor does not save translations

### ISSUE THREAD

**Issue by darizzuto** [ColdTrick/translation_editor#11]
Hi, I have a problem with translation editor, I'll explain:

Use elgg 1.9 and with all the browser plugin does not automatically save, I have no javascript error.

Thanks for your help

**Comment by darizzuto** [comment]
There has been an improvement, I noticed that not only saves the Italian translation as if translating English works!

Also disable all plugins I disappears language Italian

**Comment by jdalsem** [comment]
> There has been an improvement, I noticed that not only saves the Italian translation as if translating English works!

i am unable to reproduce this



> Also disable all plugins I disappears language Italian

you probably also disabled the plugin that provides the italian language
