### ISSUE TITLE
Support for starter project languages

### ISSUE THREAD

**Issue by Wouter0100** [ColdTrick/translation_editor#18]
Currently there doesn't seems to be support for the languages defined in the starter-project, used when utilizing composer in an Elgg project.

**Comment by jeabakker** [comment]
what do you mean? The starter project is not an Elgg mod (and doens't have any translations)

Do you mean the mods installed by the starter project? they should be detected

**Comment by Wouter0100** [comment]
That's correct, it's not a mod, but it's having it's own translations (just like the `start.php` is called and view overrides/files work). This is how individual projects should be customized using starter project.

See [here](https://github.com/Elgg/Elgg/blob/232057be79b7df14dcc43b5426d65863327fac58/engine/classes/Elgg/Application.php#L269-L295) for the code comments about loading Elgg as a composer dep (and so the root is threaded as a "plugin"). See line 287 where the root is also added as a translation path.

**Comment by jeabakker** [comment]
are we talking about the same starter project? https://github.com/Elgg/starter-project doesn't have either a `start.php` or a `/languages` dir. 

Yes', it's possible but what would be the use case? Someone made modifications to the starter project and added Elgg code in the project instead of a plugin?

**Comment by Wouter0100** [comment]
Yes, by default they doesn't exist, since it's just a blank project. But you're able to create a `start.php` and `languages`-dir in the starter-project's root.

The use case is when having project-specific changes, which you want to apply to the project (for example, a custom theme or a custom behavior in some scenario specifically for that project). When using project-starter those changes don't need to be in a separate plugin, which isn't that logical and harder to maintain. See the most PHP frameworks (Laravel, CakePHP), all work the same way.

**Comment by jdalsem** [comment]
Not going to support this. Elgg also removed loading translations from the starter projects locations (AFAIK)
