### ISSUE TITLE
No issue, question or new featured

### ISSUE THREAD

**Issue by dragonjon** [ColdTrick/translation_editor#19]
Hi guys, good work with this plugin.
The question is, there is some way to generate a complete file with the translations that already has a plugin and the ones that are added that are missing in one language and generate the php of the language to be able to collaborate with the developers of the plugins with the translations. It would be interesting to have the option.

Thanks
Jon

Updated: I look this featured in the plugin all clear

**Comment by jeabakker** [comment]
Yes, the download button generates a PHP file which a plugin developer can add to his/her project (or you can make a PR for it.

The downloaded file only contains the translated strings for that language (combined both the existing strings and the custom translated string by the translator).

For an example of what the file will look like check out https://github.com/ColdTrick/translation_editor/blob/master/languages/nl.php

Most of the time we develop a plugin with the English language file and than using translation editor to translate the plugin to Dutch (our native language)

**Comment by dragonjon** [comment]
Hi @jeabakker thanks for response. Who can make PR of the ES language to yours plugins?

Jon

**Comment by jeabakker** [comment]
anyone with a github account can make a PR, see https://help.github.com/articles/creating-a-pull-request/
