### ISSUE TITLE
Cached language generated incorrectly

### ISSUE THREAD

**Issue by beck24** [ColdTrick/translation_editor#21]
One of our sites suddenly had Russian labels on the group edit page, clearing the cache set it back to English.
I have found this can be recreated by having an account set to use Russian as the language.  Clear the cache while logged in as that account.  Then log in as an account with English as the language - the english language cache file contains Russian language strings.

eg. the start of the first line of {dataroot}/system_cache/en.lang is now

```a:5355:{s:18:"groups:description";s:16:"Описание";s:23:"groups:briefdescription";s:31:"Краткое описание";s:16:"groups:interests";s:16:"Интересы";s:16:"profile:facebook";s:8:"Facebook";s:16:"profile:linkedin";s:8:"LinkedIn";s:15:"profile:twitter";s:7:"Twitter";```

**Comment by jeabakker** [comment]
I seem to remember that we also had this problem, and fixed it. But i can't find the commit

**Comment by beck24** [comment]
I poked around in the code but couldn't find the cause of it.  I updated to 6.0 (the most recent on packagist) and still had the same issue.  If it's fixed in master can you push out a new version when you have a chance?
Please and thanks!
