### ISSUE TITLE
Not all language strings should be trimmed

### ISSUE THREAD

**Issue by beck24** [ColdTrick/translation_editor#8]
We have some language strings that need to have a space at the beginning or end of the string, and translation editor irreversibly removes that space.  The only way to restore the string seems to be disabling the plugin, but that obviously nukes all of the other translations.

Suggestion - a checkbox or something to state whether to trim the value.  It should be checked by default so trimming occurs as normal the majority of the time but can be disabled if necessary...

**Comment by jdalsem** [comment]
Can you give me an example of a usecase where you need a space? Why not do that with styling?

**Comment by beck24** [comment]
The usecase is sub-strings

eg. in an email subject
Event: Funny Hat Day has been created by Matt Beckett

Event: Funny Hat Day has been created in the Hat group by Matt Beckett

The substring is: ' in the %s group'
When translation manager trims the substring it ends up looking like

Event: Funny Hat Day has been createdin the Hat group by Matt Beckett

**Comment by jdalsem** [comment]
we could conditionally trim:
-> if the original language string contains a space at the beginning and/or end, do not trim

**Comment by beck24** [comment]
That would work for me

**Comment by darizzuto** [comment]
Hi, I have a problem with translation editor, I'll explain:

Use elgg 1.9 and with all the browser plugin does not automatically save, I have no javascript error.

Thanks for your help

**Comment by jeabakker** [comment]
@darizzuto please report this as a new issue, it has nothing to do with this issue

**Comment by darizzuto** [comment]
Excuse me
